version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - .:/var/www/
    ports:
      - 8080:80

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - ./mysql:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laradoc
    ports:
      - '6033:3306'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '8081:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password

